######################################################################
# Automatically generated by qmake (3.0) qui set 10 01:11:03 2015
######################################################################

TEMPLATE = app
TARGET = TED
INCLUDEPATH += . src

# Input
HEADERS += src/notepad.h
SOURCES += src/main.cpp src/notepad.cpp
