######################################################################
# Automatically generated by qmake (3.0) qua set 9 22:21:12 2015
######################################################################

QT += widgets

TEMPLATE = app
TARGET = bin/TED
INCLUDEPATH += ./include

# Input
VPATH += ./src ./include
HEADERS += notepad.h
SOURCES += main.cpp notepad.cpp
